"""your_message

Revision ID: 6f8091409ed5
Revises: 76e66b1b63c7
Create Date: 2026-01-02 18:53:32.919545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f8091409ed5'
down_revision: Union[str, Sequence[str], None] = '76e66b1b63c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_matches', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_matches', 'is_done',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
