"""add competition_id column to match table

Revision ID: b3e5a18cbd60
Revises: 90f9d641c71c
Create Date: 2025-12-31 13:10:13.043582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3e5a18cbd60'
down_revision: Union[str, Sequence[str], None] = '90f9d641c71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('competition_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matches', 'competitions', ['competition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matches', type_='foreignkey')
    op.drop_column('matches', 'competition_id')
    # ### end Alembic commands ###
