"""add hide_scores column to users table

Revision ID: e3916e7b5267
Revises: 58f6482e68ec
Create Date: 2026-01-26 17:25:49.670822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3916e7b5267'
down_revision: Union[str, Sequence[str], None] = '58f6482e68ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add the column as nullable first
    op.add_column('users', sa.Column('hide_scores', sa.Boolean(), nullable=True))
    
    # 2. Set the default value for all existing rows
    op.execute("UPDATE users SET hide_scores = False")
    
    # 3. Now that no rows are NULL, make it NOT NULL
    op.alter_column('users', 'hide_scores', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hide_scores')
    # ### end Alembic commands ###
